name: "Sprint 1 — Online Store Project"
description: "CS308 Course Project | Next.js + Nest.js + MySQL e-commerce platform"

columns:
  - name: 📋 Backlog
    cards:
      - "Initialize Nest.js backend (`nest new backend`)"
      - "Setup MySQL connection (TypeORM or Prisma)"
      - "Define entities: User, Product, Order, OrderDetail, Cart"
      - "Implement GET /products endpoint"
      - "Implement POST /login endpoint"
      - "Draw ER Diagram (User, Product, Order, OrderDetail, Cart)"
      - "Create SQL schema and populate Product table"
      - "Initialize Next.js frontend (`npx create-next-app frontend`)"
      - "Create basic pages: '/', '/products', '/login', '/cart'"
      - "Connect frontend to backend API"
      - "Implement dummy product list with Tailwind CSS"
      - "Build Navbar and ProductCard components"
      - "Setup .env files for DB credentials and ports"
      - "Create GitHub repo structure (frontend + backend folders)"
      - "Assign team roles and add to README"
      - "Merge first pull request successfully"
      - "Add project board link to README"

  - name: ⚙️ In Progress
    cards:
      - "Working on Nest.js API and DB integration"
      - "Building frontend layout with Tailwind"

  - name: 🧪 Testing / Review
    cards:
      - "Testing GET /products endpoint"
      - "Testing connection between frontend and backend"

  - name: ✅ Done
    cards:
      - "Successful first full-stack connection (Next.js ↔ Nest.js ↔ MySQL)"
      - "ER Diagram finalized and approved"
      - "Project setup demo ready for Sprint 1 review"
